version: '3.9'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=marcinniemczyk
            - POSTGRES_USER=marcinniemczyk
            - POSTGRES_PASSWORD=marcinniemczyk123
        container_name: db
    api:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - 8000:8000
        image: marcin_niemczyk:hexocean
        container_name: api
        depends_on:
            - db
