# Generated by Django 4.1.3 on 2022-11-22 12:15

from django.db import migrations


def create_admin_account(apps, schema_editor):
    User = apps.get_model("api", "User")
    AccountTier = apps.get_model("api", "AccountTier")
    User.objects.create_superuser(
        username="admin", password="admin", tier=AccountTier.objects.get(id=3)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_api_fixtures"),
    ]

    operations = [
        migrations.RunPython(create_admin_account),
    ]
